package l9;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import l9.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.19 22:50:57 // Generated by ComTest
 *
 */
public class PieninTest {
}