package demo7;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo7.EtsiVA.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.24 22:28:19 // Generated by ComTest
 *
 */
public class EtsiVATest {



  // Generated by ComTest BEGIN
  /** testVuodenAika22 */
  @Test
  public void testVuodenAika22() {    // EtsiVA: 22
    assertEquals("From: EtsiVA line: 23", "talvi", vuodenAika("tammi")); 
    assertEquals("From: EtsiVA line: 24", "talvi", vuodenAika("helmi")); 
    assertEquals("From: EtsiVA line: 25", "kevät", vuodenAika("maalis")); 
    assertEquals("From: EtsiVA line: 26", "kevät", vuodenAika("huhti")); 
    assertEquals("From: EtsiVA line: 27", "syksy", vuodenAika("syys")); 
    assertEquals("From: EtsiVA line: 28", "???", vuodenAika("mätä")); 
  } // Generated by ComTest END
}