package demo7;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static demo7.EtsiVA.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.05.23 22:49:52 // Generated by ComTest
 *
 */
public class EtsiVATest {


  // Generated by ComTest BEGIN
  /** testVuodenAika16 */
  @Test
  public void testVuodenAika16() {    // EtsiVA: 16
    assertEquals("From: EtsiVA line: 17", "talvi", vuodenaika("tammi")); 
    assertEquals("From: EtsiVA line: 18", "talvi", vuodenaika("helmi")); 
    assertEquals("From: EtsiVA line: 19", "kevät", vuodenaika("maalis")); 
    assertEquals("From: EtsiVA line: 20", "kevät", vuodenaika("huhti")); 
    assertEquals("From: EtsiVA line: 21", "syksy", vuodenaika("syys")); 
    assertEquals("From: EtsiVA line: 22", "???", vuodenaika("mätä")); 
  } // Generated by ComTest END
}